//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrelimWQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRespons
    {
        public int ResponseId { get; set; }
        public int ParticipantId { get; set; }
        public int ResponseTypeId { get; set; }
        public System.DateTime DateResponseLogged { get; set; }
        public bool Ambiguous { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Signature { get; set; }
    
        public virtual MailParticipant MailParticipant { get; set; }
        public virtual MailResponseType MailResponseType { get; set; }
    }
}
