//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrelimWQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailResponseConsent
    {
        public int LinkId { get; set; }
        public int ResponseId { get; set; }
        public int ConsentId { get; set; }
        public int Selected { get; set; }
    
        public virtual MailRespons MailRespons { get; set; }
    }
}
